### PR TITLE
Support qwenvl model for HPU

### PR DESCRIPTION
**Pull request by yingjie-han**
This PR aims to support qwenvl vision infer on HPU.

### **Issue to solve**
The function merge_multimodal_embeddings() in utils.py has dynamic problem on HPU.

### **Solution**
Flatten the embeddings tensor , and use index_put_() to merge the multimodal embeddings in qwen.py instead of calling merge_multimodal_embeddings() in utils.py.

### **Test**
**Single image**
` python examples/offline_inference/vision_language.py -m qwen_vl`

**Multiple images**
`python examples/offline_inference/vision_language_multi_image.py -m qwen_vl_chat`

### CODE REVIEW

**Comment by yingjie-han** [comment]
@michalkuligowski @jikunshang @PatrykWo could you help to review the code?

File: vllm/model_executor/models/qwen.py [hunk 1]
```diff
@@ -975,9 +975,11 @@ def get_input_embeddings(
 
         if multimodal_embeddings is not None:
             assert self.transformer.visual is not None
-            inputs_embeds = merge_multimodal_embeddings(
-                input_ids, inputs_embeds, multimodal_embeddings,
-                self.transformer.visual.image_pad_id)
+            batch_size, seq_length, hidden_size = inputs_embeds.shape
```
[the remark this answers is not in the document]
Comment (yingjie-han) [reply vllm/model_executor/models/qwen.py]: Merge conflicts has been solved. Please review it. Thanks

File: vllm/model_executor/models/qwen_vl.py [hunk 2]
```diff
@@ -761,9 +761,11 @@ def get_input_embeddings(
         inputs_embeds = self.transformer.get_input_embeddings(input_ids)
 
         if multimodal_embeddings is not None:
-            inputs_embeds = merge_multimodal_embeddings(
-                input_ids, inputs_embeds, multimodal_embeddings,
-                self.transformer.visual.image_pad_id)
+            batch_size, seq_length, hidden_size = inputs_embeds.shape
```
Comment (michalkuligowski) [inline vllm/model_executor/models/qwen_vl.py:764]: This shouldnt be in model definition. Please try fixing the merge_multimodal_embeddings method. You can check whether its hpu to call your implementation

**Review by michalkuligowski — CHANGES_REQUESTED** [review]

File: vllm/model_executor/models/qwen_vl.py (hunk 2 above)
Comment (yingjie-han) [reply vllm/model_executor/models/qwen_vl.py]: @michalkuligowski ,I moved the implementation to merge_multimodal_embeddings method. Please check it. Thanks.

**Review by michalkuligowski — APPROVED** [review]

File: vllm/model_executor/models/utils.py [hunk 3]
```diff
@@ -16,6 +16,9 @@
 from vllm.multimodal import MultiModalPlaceholderMap, NestedTensors
 from vllm.sequence import IntermediateTensors
 from vllm.utils import is_pin_memory_available
+from vllm.platforms import current_platform
```
Comment (michalkuligowski) [inline vllm/model_executor/models/utils.py:19]: Precommit suite failed, please fix isort and fluff issues

**Review by michalkuligowski — CHANGES_REQUESTED** [review]

File: vllm/model_executor/models/utils.py (hunk 3 above)
Comment (yingjie-han) [reply vllm/model_executor/models/utils.py]: @michalkuligowski isort and fluff issues are fixed

**Review by pk1d3v — COMMENTED** [review]
IMO, it would be great if we can incorporate check for expected and actual number of image token to merge, like original `_merge_multimodal_embeddings` does:

```py
    if flattened.shape[0] != num_expected_tokens:
        expr = _embedding_count_expression(multimodal_embeddings)
        raise ValueError(
            f"Attempted to assign {expr} = {flattened.shape[0]} "
            f"multimodal tokens to {num_expected_tokens} placeholders")
```

It would help to catch errors early on.

File: vllm/model_executor/models/utils.py [hunk 4]
```diff
@@ -376,6 +379,39 @@ def _merge_multimodal_embeddings(
...
+                                            device=input_ids.device)
+        is_multimodal = [
+            torch.isin(input_ids.reshape(-1), placeholder_token_id)
+        ]
+    else:
+        is_multimodal = [input_ids.reshape(-1) == placeholder_token_id]
+        
+    batch_size, seq_length, hidden_size = inputs_embeds.shape
+    inputs_embeds = inputs_embeds.reshape(-1, hidden_size)
+    multimodal_embeddings = multimodal_embeddings.reshape(-1, hidden_size)
```
Comment (pk1d3v) [inline vllm/model_executor/models/utils.py:409]: This line fails if `multimodal_embeddings` is list or tuple of `Tensor`s. This scenario is possible since it's type hint is `NestedTensors`.
```
[rank0]:   File "/app/vllm-fork/vllm/model_executor/models/utils.py", line 383, in _merge_multimodal_embeddings_hpu
[rank0]:     multimodal_embeddings = multimodal_embeddings.reshape(-1, hidden_size)
[rank0]: AttributeError: 'tuple' object has no attribute 'reshape'
```
Probably, we can utilize `_flatten_embeddings(multimodal_embeddings)` to overcome this. What do you think ?

**Comment by yingjie-han** [comment]
It seems that the original code works well on driver 1.20, so I close this PR.
